name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: composer:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: composer install
      - name: Zip build
        run: zip -r vendor.zip vendor
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: moosh-vendor
          path: vendor.zip
            
  run_8-2:
    runs-on: ubuntu-latest
    container: php:8.2-rc-fpm-alpine
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Remove vendor folder
        run:  rm -rf vendor && ls && pwd
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: moosh-vendor
      - name: Unzip build
        run: ls && unzip vendor.zip -d vendor
      - name: Run code
        run:  ls vendor && php moosh.php
        
